linters:
  enable:
    - govet
    - revive
    - errcheck
    - staticcheck
    - unused
    - paralleltest

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - golint
        - staticcheck

