codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto
  range: "70...100"
  precision: 2
  round: down
  adjustments:
    - title: Ignore mocks directory
      comment: This ignores the mock files in internal/client/mocks directory
      paths:
        - "!internal/client/mocks/**"
